### ISSUE TITLE
Redirect loop from #14

### ISSUE THREAD

**Issue by zachleat** [NebraskaJS/nejsconf.com#15]
Merge from #14 resulted in 

![image](https://cloud.githubusercontent.com/assets/39355/7734595/b37f395c-fefc-11e4-92e4-0ad7c9c90ace.png)

when accessing `/register` or `/register.php`

**Comment by jmhobbs** [comment]
Dang, I had a cached 301 in my test browser.  I'll find a fix, sorry :-\

**Comment by zachleat** [comment]
I believe I just removed the .htaccess redirect for this—all of the site links go to `/register` just fine anyway. It just won’t redirect if you go to `/register.php`
