### ISSUE TITLE
Fix https://www.nejsconf.com/ redirect

### ISSUE THREAD

**Issue by zachleat** [NebraskaJS/nejsconf.com#19]
(lots of scary error messages)

For example, Chrome/Mac

![image](https://cloud.githubusercontent.com/assets/39355/8764065/17e2eaba-2d83-11e5-858a-0bcd2855fe47.png)

We just need to redirect to https://nejsconf.com/ instead, since that’s canonical. Non https http://www.nejsconf.com/ redirects fine.

**Comment by jerodsanto** [comment]
Do we have a wildcard cert? If not I think fixing this would require we purchase another cert for the www subdomain.

**Comment by zachleat** [comment]
Just tested:

http://nejsconf.com works
http://www.nejsconf.com works
https://nejsconf.com canonical
https://www.nejsconf.com/ works
