### ISSUE TITLE
Remove static on hover?

### ISSUE THREAD

**Issue by codyjames** [NebraskaJS/nejsconf.com#5]
I feel like the static on hover doesn't quite make sense (makes it feel more like a TV) and doesn't fit with the aesthetic thus far. Also, I think if we remove it the cursor takeover effect (which I love, BTW) would feel even more awesome.

I would remove the drop-shadow effect as well but don't care too much either way.

**Comment by jmhobbs** [comment]
Looks closed in 4092d52566d48a2ddf09c060e46c47e6163db99b

**Comment by codyjames** [comment]
Zach and I have an idea of something that could replace this for the next version.

**Comment by jmhobbs** [comment]
:snake:

**Comment by jerodsanto** [comment]
I would pay :moneybag: :moneybag: to be able to play :snake: in that screen. Also I'd volunteer to code this up if everybody wants it to be a thing

**Comment by codyjames** [comment]
That'd be nuts. And super awesome.
