### ISSUE TITLE
Email field feels bulky

### ISSUE THREAD

**Issue by codyjames** [NebraskaJS/nejsconf.com#6]
This is my fault as I neglected to mock-up this piece. If I get some time soon I may refine this a bit.

Also, center-aligned form fields feel a bit awkward (again, my mock-ups didn't suggest any easy solutions to this).

**Comment by jmhobbs** [comment]
I also get a border when in focus, which feels weird to me on a rounded field.

![Border](http://cl.ly/image/0F0p2Q2n2e3p/Image%202015-02-10%20at%201.15.16%20PM.png)

**Comment by codyjames** [comment]
@jmhobbs Yeah, good catch. I can fix that up when I refine this.

**Comment by jerodsanto** [comment]
Also "e-mail" is the Absolute Worst. Hyphens what

**Comment by jmhobbs** [comment]
Should totally be an emdash.  

e—mail

**Comment by codyjames** [comment]
Yeah, I prefer an em dash. E—mail.

**Comment by codyjames** [comment]
HAHAHAHA. Same jokes!

**Comment by jerodsanto** [comment]
How about just: Electronic-Mail

**Comment by zachleat** [comment]
Closing this, we don’t have this field on the site anymore.
